language: node_js
deploy:
  provider: elasticbeanstalk
  access_key_id: AKIAJFVLYCOVY23JFWJA
  secret_access_key:
    secure: O5vIhxf/Ok7kHCIQP2IrEn91s8gz8C2sM5h837PsQXgNv/gkbDcvUbMeW9ni4aRVWKrJFWpM1Qvz8shqscNTeOfihpKO9rpFIY/zQQ6dcJt6Mg0oJ2SY02qWiCBS7Ox3z1y0VTI89PLW1a2fLpGmvtb+cAaUdAPLVlP5qRmnvsgXSOY1tpuksRQrv/tkKPqrB50eI+JILIQlLTYPOKcZSlvvyG/tJVNH5ybUpNKrVHhdfu3aS9VbRjx57fPKqWuhlJejjg990bSp0HKnwCvTOr/f+IcTgZuh9S08jF3zH4AUQYoJ2iG3TjRwQOkkIrwSTOyJAgc6p2xht606pPMHDfwSiQnW8lhkF7iPpZSrjiNfCsRYf/Sx7PMLBzlamwNbgaoa3S6hsxoh6PkkcchGpQAEjNAzPiWl7lWyTBO2rfxz/MbTnRDtAkXtxSVaWAEXU0Ahh5ohkc67OPDpuuZbwUAGqnBsiSogFyQuKS3wyWJSFTRcRCBMT4s5UpNr8y7ovKIfCQgzw8ju2kUlz0EowS4bDIjkAyfXx1E/jRAAfVG4rq224ZUNad6MIUmufQ2xb65bSSpGQ3xv+SMP12yRkso8luLgXpfJNx01ENTphNFe9NHwQRPRlzhGgc5PYYponvosbQXwJOVZA2NNEMQPlQcEN28jklhtbv2nJb3DQkE=
  region: ap-northeast-2
  app: pocketmon
  env: pocketmon-env
  on:
    repo: skatpgusskat/pocketmonname
